### ISSUE TITLE
[Tree] It's possible for a child element become a root?

### ISSUE THREAD

**Issue by giovkanata** [KnpLabs/DoctrineBehaviors#177]
Premising that I'm new with Matherialized Path and this library, I've a CRUD controller for categories in which I used Tree behavior (combined with translatable) and all works as expected but when I want to change to a root a child element of the tree (with or without sub-childs) this doesn't work.
It's the right behavior or I've missed something?
Do I need to implement it by myself (I haven't seen any method to achieve this in the library) and if yes, what is the best approach?
To select the parent category I've added a ```$parent``` property on my category class (not mapped) that is used only to populate a parent hierarchical selection in the form category.
Any help pointing me in the right direction will be really appreciated.

**Comment by docteurklein** [comment]
Hi!
Good question :) I can't give a precise answer, but it should definitly be possible.
It would be awesome if you could provide a failing test case (a new unit test or something) that could be use to reproduce it.

It would also be good to see if the problem comes from the persistance (is the path correctly stored in sql ?), or a build problem (is the `buildTree` method able to re-generate the tree based on paths ?)
or a `Node` problem (are we able to generate a correct path?)

**Comment by CharlyPoppins** [comment]
I use this
```
if (null === $this->getCategorieParente()) {
	$this->setMaterializedPath('/');
} else {
	$this->setChildNodeOf($this->getCategorieParente());
}
```
**setChildNodeOf** should take **null** it will be simplier :)
