### ISSUE TITLE
TranslatableSubscriber: what about using protected instead of private

### ISSUE THREAD

**Issue by fpiccinali** [KnpLabs/DoctrineBehaviors#251]
Thanks to injection, it is easy to replace TranslatableSubscriber by our custom Subscriber. 

But if we want to benefit from the original Subscriber, it is difficult to use extends.

For instance:

```
class myCustomTranslatableSubscriber extends \Knp\DoctrineBehaviors\ORM\Translatable\TranslatableSubscriber {
...
```

In this case we need to copy 80% of original code because of private properties and private methods.
If we just need to customise one method, we can not override just one. We must copy all private methods and properties.

What is the reason to restrict so severely ? 

Could not we use "protected" instead ?

**Comment by calumbrodie** [comment]
This is a very simple class, why not just duplicate the very simple logic that exists here...

**Comment by nifr** [comment]
@calumbrodie I think this discussion shouldn't be about effort ... but about design.

I'm in favor of changing from private to protected properties to make extending easier at this point.

**Comment by calumbrodie** [comment]
Sorry my mistake I was confusing this class with Knp\DoctrineBehaviors\ORM\Translatable\CurrentLocaleCallable.

**Comment by docteurklein** [comment]
The best design is the one allowing open/closed principle.
The behavior should be modifiable without having to modify the class, nor extending it.
I should have put the class `final` to make it explicit.
If it was final, we would be forced to refaoctor it so that it is reusable by composition f.e.

Now, to be pragmatic, we could allow **some** methods or properties to be overridable, but not dumbly search and replace all private with protected.

If you have a good use case, we can maybe make an exception,t but I tend to agree with @calumbrodie  in that custom behaviors could have their own class, at the cost of duplication.
But I prefer having closed classes in the lib and you having to maintain a duplicate than me having to maintain BC on all the classes :)

**Comment by EVDW** [comment]
@docteurklein (hello you from 2015!) I have a good case for you!
Related to [this issue](https://github.com/KnpLabs/DoctrineBehaviors/issues/563), I have to add just a third argument on the private method `isTranslatable`, but I can't just override this method because it's private...

**Comment by docteurklein** [comment]
helllooooo @EVDW :) :) 
maybe a simple solution would be to copy the trait contens into your won class and change the visibility to public ?

cheers :)
