### ISSUE TITLE
[Translatable] ->translate() don't work when object in session 

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#310]
Hi,
I'm storing entites in session like this :
```
array_push($panier, array("type" => $type, "id" => $id, "qte" => $qte, "objet" => $objet));
$session->set('panier', $panier);
```
then I didn't manage to get my translations :
```
var_dump($session->get('panier')[0]["objet"]->translate('fr')->getTitre());
```
 Any idea of what I am missing ?

**Comment by akovalyov** [comment]
My guess - your object is out of Doctrine UOW context and you should  bring it back via [`$em->merge($yourObject)`](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#merging-entities), so that Doctrine can transparently hydrate translations. Or, you should fetch it eagerly before putting into session (but I am not sure about serialization and stuff).

**Comment by CharlyPoppins** [comment]
:+1: 
Thanks for your answer, this works fine.
I'm using `$em->detach($entity)` before adding the item in my session, then I use `$em->merge($entity) `before sending it in my Response.
