### ISSUE TITLE
[Translateable] Attempted to call an undefined method named "setDefaultLocale" of class ...

### ISSUE THREAD

**Issue by ibasaw** [KnpLabs/DoctrineBehaviors#314]
hi,
i use this with sylius, but i got errors on many entities which doesn't have the property locale on the main entity but got it in an abstract class; there is a conflict.

```
Attempted to call an undefined method named "setDefaultLocale" of class "Proxies\__CG__\Sylius\Component\Core\Model\Taxon".
```

How to disabled the TranslatableSubscriber for these entities ?

**Comment by pjedrzejewski** [comment]
Hi @ibasaw, I just ran into this issue while plugging in Sylius into existing Symfony project, which is using KNP's DoctrineBehaviors. Seems like the ClassAnalyzer is not checking the full trait namespace. So our Sylius traits "TranslatableTrait" conflicts here. I think the solution would be to check for fully namespaced trait from KNP. I can submit a PR if it will be accepted anytime soon! :) /cc @docteurklein

**Comment by ibasaw** [comment]
will be great ! @pjedrzejewski

**Comment by daum** [comment]
I think this may still be an issue - if you have an entity which has 'setCurrentLocale' on it, as a function then the TranslatableSubscriber in the setLocales routine is going to try to do setCurrentLocale and setDefaultLocale on the object, even though it doesn't actually implement the translatable check.

https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L317 is the line i'm referencing.

I would think we'd want to instead check if it has the translatable trait instead via the isTranslatable method rather than just relying on the function check.  What are your thoughts?

**Comment by ibasaw** [comment]
news ?

**Comment by docteurklein** [comment]
this trait analyzer mess is just overcomplicating things. Once we go "all interfaces", those problems should vanish. see #241

**Comment by ibasaw** [comment]
news ?
