### ISSUE TITLE
Translatable: Use of composite primary key in translation entity

### ISSUE THREAD

**Issue by user1024a** [KnpLabs/DoctrineBehaviors#341]
I have an entity:
**StructureA** with properties:
id
_property1_
_property2_
and second entity:
**StructureAI18n** with properties:
_property3_ PK
_id_ PK linked to id in StructureA
_property4_
The question is if it's possible to use composite primary key in translation entity? Doctrine throws mapping exception.
Some clarification: in entity StructureA I want to store properties which I do not want to translate. In entity StructureAI18n there are properties which will be translated. Methods `getTranslationEntityClass` and `getTranslatableEntityClass` are overriden globally by defining custom traits (as described in the docs). Property3 and id in StructureAI18n both make composite primary key. When I try to persist entity into database the following error is thrown: `Doctrine\ORM\Mapping\MappingException: Single id is not allowed on composite primary key in entity Path\To\StructureAI18n`.

**Comment by docteurklein** [comment]
that's a good question! I never tried to use it with composite keys.

I would advise you to try to do the mapping manually for now.
Instead of using the default mapping (https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L96), you define it yourself.

Maybe the subscriber won't let you, so you might have to disable it in order to test.
