### ISSUE TITLE
Add locale code to the assert message

### ISSUE THREAD

**Issue by martinadamec** [KnpLabs/DoctrineBehaviors#352]
Hi everyone,

I have a entity like this:
```
class TestTranslation
{
	use ORMBehaviors\Translatable\Translation;

	/**
	 * @var int
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @var string
	 * @ORM\Column(name="name", type="string", length=255)
	 * @Assert\NotBlank(message = "[{{ locale }}] This value should not be blank.")
	 */
	protected $name;
}
```
I´m trying to figure how to pass a locale code into assert error message. Do you have any tips, please?

It´s really weird when the user receive 5 message with the same content. It looks like one error what is printed 5 times, but it is 5 "different" error, each on different input.

Thank you.

**Comment by docteurklein** [comment]
hey there! My guess is that the NotBlank validator at the `$name` property  level is not able to access other properties of the same object. You'd have to attach a (callback?) validator at the object (instance of TestTranslation) level in order to access both fields and provide useful feedback to the user.
Hope it helps!
