### ISSUE TITLE
[Help] Tree/Node Behavior with Auto Increment?

### ISSUE THREAD

**Issue by skrosoft** [KnpLabs/DoctrineBehaviors#366]
Hello,

Is it posible to use auto-increment with the tree/node behavior?

If not, how can I have an ID before the persist call?

I get the following error:

`You must provide an id for this node if you want it to be part of a tree.`

Maybe the librarie should use PostUpdate to get the ID and finally generate the path.

Imposible to use this behavior for me, I have no ID before to persist my entities.

Do someone has any example of implementation of this behavior?

Thanks.

**Comment by skrosoft** [comment]
Ok, I had to add the folowing function in my entity:

```
    /**
     * Get the node id
     *
     * @return int
     */
    public function getNodeId()
    {
        return is_null($this->id) ? -1 : $this->id;
    }
```

It now work fine, of course, I have to persist the parent before to persist the child.

**Comment by Einenlum** [comment]
Hi @skrosoft.

I'm not sure this library should bother with autoincrement issues.
One thing you can do to have an ID before persisting in database, is to generate an UUID into your code directly, instead of letting the database doing it.
Exposing an auto-increment ID is not considered as a good practice anyway.

This way, you guarantee a more secure way of storing IDs and at the same time, you keep the control of IDs out of the DB process.

**Comment by psren** [comment]
@Einenlum exactly what I did.
The only change I had to do was changing the field because VARCHAR(255) was not enough.

```php
/**
 * @ORM\Column(type="text")
 */
protected $materializedPath = '';
```

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
