### ISSUE TITLE
Update Translate

### ISSUE THREAD

**Issue by apropsi** [KnpLabs/DoctrineBehaviors#394]
When I call to update:
public function save(Services $services) {        
        if (!$services->getId()) {
// INSERT
            $this->getEntityManager()->persist($services);
////////////
        } else {
// UPDATE
            $services = $this->getEntityManager()->persist($services);
////////////
        }
        $this->getEntityManager()->flush();
}

Insert goes well but update just insert a new row.... Any thought?

Thanks in advance

**Comment by roman-1983** [comment]
Try to call `$services->mergeNewTranslations()` before `$this->getEntityManager()->flush()`.

**Comment by brukrneti** [comment]
Have you ever fixed this? mergeNewTranslations calls addTranslation method which triggers insertion of a new row. Therefore it returns error _Integrity constraint violation: 1062 Duplicate entry \u002761-en\u0027 for key \u0027table_name_unique_translation\u0027"}_ since it tries to insert same id for already existing row... I've tried to find method for updating translation entries but I can't seem to find it..

**Comment by brukrneti** [comment]
Ok, I have finally fixed this!

I was trying to implement update method for REST API. Before every update, you have to manually set translates to the new entity.

Let's say you build the entity from the request params:

- the idea is to load the old translations from the existing entity in the database. You can add this method to your entity

`public function setTranslations($translations): self
    {
        $this->translations = $translations;
        return $this;
    }`

and call it before 

`$entity->translate('locale')->setTitle('Awesome title')`

and _mergeNewTranslations()_

Hope this will help someone as there is nothing about _UPDATE_ operation in the README.

**Comment by TomasVotruba** [comment]
Could you send failing test to reproduce this?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Test case is needed for v2 that has many changes already
