### ISSUE TITLE
[Translatable] doTranslate function need fixed

### ISSUE THREAD

**Issue by langziyang** [KnpLabs/DoctrineBehaviors#615]
there is example:
 we have two or more language like: zh_cn and en;
first only set zh_cn:

$c=new Category();
$c->translate('zh_CN')->setName('for zh_cn');
$em->persist($c);
$c->mergeNewTranslations();
$em->flush();

($c->getId() =1)

next:
$c= $repository->find(1);
$c->translate('zh_CN')->setName('for zh_cn modify');
$c->translate('en')->setName('for en');
$c->mergeNewTranslations();
$em->flush();

when flush,the database only have zh_cn

**Comment by TomasVotruba** [comment]
Hi, thank for the issue report. 
We'll need a failing test case in a pull-request, so we're able to replicate it.

**Comment by TBurtin** [comment]
Hi,

Same issue for me, but it was because the method translate() use $fallbackToDefault = true as second parameter.

So if your CategoryTranslation does not exist when you call $c->translate('en'), it will not create it, but load the translation in your default locale (zh_CN) 

$c->translate('en',false)->setName('for en');  should work.

**Comment by TomasVotruba** [comment]
Closing for lack of failing test case.
